# Environment variables
job:
  url: http://job:8082

company:
  url: http://company:8081

review:
  url: http://review:8083

spring:
  application:
    name: review
  datasource:
    url: jdbc:postgresql://postgres:5432/review
    username: vato
    password: 1
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create-drop
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8083
  shutdown: graceful

# Eureka client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

# Zipkin
management:
  tracing:
    sampling:
      probability: 1.0
  # Prometheus
  endpoints:
    web:
      exposure:
        include: prometheus
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans