# Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: company
          uri: lb://COMPANY
          predicates:
            - Path=/companies/**
        - id: job
          uri: lb://JOB
          predicates:
            - Path=/jobs/**
        - id: review
          uri: lb://REVIEW
          predicates:
            - Path=/reviews/**
        - id: eureka
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/main
          filters:
            - SetPath=/
        - id: eureka-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true

server:
  port: 8084
  shutdown: graceful

# Zipkin
management:
  tracing:
    sampling:
      probability: 1.0
  # Prometheus
  endpoints:
    web:
      exposure:
        include: prometheus

# Logging
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE