# Environment variables
job:
  url: http://localhost:8082

company:
  url: http://localhost:8081

review:
  url: http://localhost:8083

spring:
  application:
    name: job
  datasource:
    url: jdbc:postgresql://localhost:5050/job
    username: vato
    password: 1
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  config:
    import: optional:configserver:http://localhost:8080

server:
  port: 8082
  shutdown: graceful

# Eureka client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

# Zipkin
management:
  tracing:
    sampling:
      probability: 1.0
  # Actuator and Prometheus
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: always
