# Environment variables
job:
  url: http://localhost:8082

company:
  url: http://localhost:8081

review:
  url: http://localhost:8083


spring:
  application:
    name: company
  datasource:
      url: jdbc:postgresql://localhost:5050/company
      username: vato
      password: 1
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create-drop
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8081
  shutdown: graceful

# Eureka Client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Zipkin
management:
  tracing:
    sampling:
      probability: 1.0
  # Prometheus
  endpoints:
    web:
      exposure:
        include: prometheus